/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MatchManager } from "./MatchManager";
export type { TournamentManager } from "./TournamentManager";
