/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MatchManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MATCH_TIMEOUT"
      | "cancelMatch"
      | "claimTimeout"
      | "createMatch"
      | "joinMatch"
      | "matchCount"
      | "matches"
      | "owner"
      | "reportResult"
      | "setTrustedSigner"
      | "transferOwnership"
      | "trustedSigner"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchCancelled"
      | "MatchCreated"
      | "MatchJoined"
      | "MatchResult"
      | "MatchTimeoutClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MATCH_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMatch",
    values: [BigNumberish, boolean, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reportResult",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedSigner",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MATCH_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinMatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matchCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedSigner",
    data: BytesLike
  ): Result;
}

export namespace MatchCancelledEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    creator: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    creator: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    creator: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    creator: AddressLike,
    goalsTarget: BigNumberish,
    isFree: boolean
  ];
  export type OutputTuple = [
    matchId: bigint,
    creator: string,
    goalsTarget: bigint,
    isFree: boolean
  ];
  export interface OutputObject {
    matchId: bigint;
    creator: string;
    goalsTarget: bigint;
    isFree: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchJoinedEvent {
  export type InputTuple = [matchId: BigNumberish, challenger: AddressLike];
  export type OutputTuple = [matchId: bigint, challenger: string];
  export interface OutputObject {
    matchId: bigint;
    challenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchResultEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    winner: AddressLike,
    totalPayout: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    winner: string,
    totalPayout: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    winner: string;
    totalPayout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchTimeoutClaimedEvent {
  export type InputTuple = [matchId: BigNumberish, claimer: AddressLike];
  export type OutputTuple = [matchId: bigint, claimer: string];
  export interface OutputObject {
    matchId: bigint;
    claimer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MatchManager extends BaseContract {
  connect(runner?: ContractRunner | null): MatchManager;
  waitForDeployment(): Promise<this>;

  interface: MatchManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MATCH_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  cancelMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTimeout: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMatch: TypedContractMethod<
    [
      goalsTarget: BigNumberish,
      isFree: boolean,
      stakeAmount: BigNumberish,
      stakeToken: AddressLike
    ],
    [bigint],
    "payable"
  >;

  joinMatch: TypedContractMethod<[matchId: BigNumberish], [void], "payable">;

  matchCount: TypedContractMethod<[], [bigint], "view">;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        creator: string;
        challenger: string;
        winner: string;
        goalsTarget: bigint;
        isFree: boolean;
        isOpen: boolean;
        isCompleted: boolean;
        stakeAmount: bigint;
        stakeToken: string;
        createdAt: bigint;
        timeoutClaimed: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  reportResult: TypedContractMethod<
    [matchId: BigNumberish, winner: AddressLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  setTrustedSigner: TypedContractMethod<
    [signer: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedSigner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MATCH_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTimeout"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<
    [
      goalsTarget: BigNumberish,
      isFree: boolean,
      stakeAmount: BigNumberish,
      stakeToken: AddressLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "joinMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "matchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        creator: string;
        challenger: string;
        winner: string;
        goalsTarget: bigint;
        isFree: boolean;
        isOpen: boolean;
        isCompleted: boolean;
        stakeAmount: bigint;
        stakeToken: string;
        createdAt: bigint;
        timeoutClaimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reportResult"
  ): TypedContractMethod<
    [matchId: BigNumberish, winner: AddressLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTrustedSigner"
  ): TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedSigner"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MatchCancelled"
  ): TypedContractEvent<
    MatchCancelledEvent.InputTuple,
    MatchCancelledEvent.OutputTuple,
    MatchCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchJoined"
  ): TypedContractEvent<
    MatchJoinedEvent.InputTuple,
    MatchJoinedEvent.OutputTuple,
    MatchJoinedEvent.OutputObject
  >;
  getEvent(
    key: "MatchResult"
  ): TypedContractEvent<
    MatchResultEvent.InputTuple,
    MatchResultEvent.OutputTuple,
    MatchResultEvent.OutputObject
  >;
  getEvent(
    key: "MatchTimeoutClaimed"
  ): TypedContractEvent<
    MatchTimeoutClaimedEvent.InputTuple,
    MatchTimeoutClaimedEvent.OutputTuple,
    MatchTimeoutClaimedEvent.OutputObject
  >;

  filters: {
    "MatchCancelled(uint256,address,uint256)": TypedContractEvent<
      MatchCancelledEvent.InputTuple,
      MatchCancelledEvent.OutputTuple,
      MatchCancelledEvent.OutputObject
    >;
    MatchCancelled: TypedContractEvent<
      MatchCancelledEvent.InputTuple,
      MatchCancelledEvent.OutputTuple,
      MatchCancelledEvent.OutputObject
    >;

    "MatchCreated(uint256,address,uint8,bool)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchJoined(uint256,address)": TypedContractEvent<
      MatchJoinedEvent.InputTuple,
      MatchJoinedEvent.OutputTuple,
      MatchJoinedEvent.OutputObject
    >;
    MatchJoined: TypedContractEvent<
      MatchJoinedEvent.InputTuple,
      MatchJoinedEvent.OutputTuple,
      MatchJoinedEvent.OutputObject
    >;

    "MatchResult(uint256,address,uint256)": TypedContractEvent<
      MatchResultEvent.InputTuple,
      MatchResultEvent.OutputTuple,
      MatchResultEvent.OutputObject
    >;
    MatchResult: TypedContractEvent<
      MatchResultEvent.InputTuple,
      MatchResultEvent.OutputTuple,
      MatchResultEvent.OutputObject
    >;

    "MatchTimeoutClaimed(uint256,address)": TypedContractEvent<
      MatchTimeoutClaimedEvent.InputTuple,
      MatchTimeoutClaimedEvent.OutputTuple,
      MatchTimeoutClaimedEvent.OutputObject
    >;
    MatchTimeoutClaimed: TypedContractEvent<
      MatchTimeoutClaimedEvent.InputTuple,
      MatchTimeoutClaimedEvent.OutputTuple,
      MatchTimeoutClaimedEvent.OutputObject
    >;
  };
}
