/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TournamentManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelTournament"
      | "createTournament"
      | "distributePrizes"
      | "isPlayerInTournament"
      | "joinTournament"
      | "owner"
      | "tournamentCount"
      | "tournaments"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PlayerJoined"
      | "TournamentCancelled"
      | "TournamentCreated"
      | "TournamentEnded"
      | "TournamentStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTournament",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributePrizes",
    values: [BigNumberish, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPlayerInTournament",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tournamentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tournaments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributePrizes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPlayerInTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "joinTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tournamentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournaments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [tournamentId: BigNumberish, player: AddressLike];
  export type OutputTuple = [tournamentId: bigint, player: string];
  export interface OutputObject {
    tournamentId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentCancelledEvent {
  export type InputTuple = [tournamentId: BigNumberish];
  export type OutputTuple = [tournamentId: bigint];
  export interface OutputObject {
    tournamentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentCreatedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    creator: AddressLike,
    entryFee: BigNumberish,
    size: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    creator: string,
    entryFee: bigint,
    size: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    creator: string;
    entryFee: bigint;
    size: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentEndedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    winner: AddressLike,
    prizeAmount: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    winner: string,
    prizeAmount: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    winner: string;
    prizeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentStartedEvent {
  export type InputTuple = [tournamentId: BigNumberish];
  export type OutputTuple = [tournamentId: bigint];
  export interface OutputObject {
    tournamentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TournamentManager extends BaseContract {
  connect(runner?: ContractRunner | null): TournamentManager;
  waitForDeployment(): Promise<this>;

  interface: TournamentManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelTournament: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTournament: TypedContractMethod<
    [size: BigNumberish, entryFee: BigNumberish, entryToken: AddressLike],
    [bigint],
    "nonpayable"
  >;

  distributePrizes: TypedContractMethod<
    [
      tournamentId: BigNumberish,
      firstPlace: AddressLike,
      secondPlace: AddressLike,
      thirdPlace: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isPlayerInTournament: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  joinTournament: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  tournamentCount: TypedContractMethod<[], [bigint], "view">;

  tournaments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint, bigint, bigint, bigint, string] & {
        creator: string;
        entryFee: bigint;
        entryToken: string;
        size: bigint;
        playerCount: bigint;
        state: bigint;
        totalPrizePool: bigint;
        winner: string;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelTournament"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTournament"
  ): TypedContractMethod<
    [size: BigNumberish, entryFee: BigNumberish, entryToken: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributePrizes"
  ): TypedContractMethod<
    [
      tournamentId: BigNumberish,
      firstPlace: AddressLike,
      secondPlace: AddressLike,
      thirdPlace: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isPlayerInTournament"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinTournament"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tournamentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tournaments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint, bigint, bigint, bigint, string] & {
        creator: string;
        entryFee: bigint;
        entryToken: string;
        size: bigint;
        playerCount: bigint;
        state: bigint;
        totalPrizePool: bigint;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentCancelled"
  ): TypedContractEvent<
    TournamentCancelledEvent.InputTuple,
    TournamentCancelledEvent.OutputTuple,
    TournamentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TournamentCreated"
  ): TypedContractEvent<
    TournamentCreatedEvent.InputTuple,
    TournamentCreatedEvent.OutputTuple,
    TournamentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentEnded"
  ): TypedContractEvent<
    TournamentEndedEvent.InputTuple,
    TournamentEndedEvent.OutputTuple,
    TournamentEndedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentStarted"
  ): TypedContractEvent<
    TournamentStartedEvent.InputTuple,
    TournamentStartedEvent.OutputTuple,
    TournamentStartedEvent.OutputObject
  >;

  filters: {
    "PlayerJoined(uint256,address)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;

    "TournamentCancelled(uint256)": TypedContractEvent<
      TournamentCancelledEvent.InputTuple,
      TournamentCancelledEvent.OutputTuple,
      TournamentCancelledEvent.OutputObject
    >;
    TournamentCancelled: TypedContractEvent<
      TournamentCancelledEvent.InputTuple,
      TournamentCancelledEvent.OutputTuple,
      TournamentCancelledEvent.OutputObject
    >;

    "TournamentCreated(uint256,address,uint256,uint8)": TypedContractEvent<
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;
    TournamentCreated: TypedContractEvent<
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;

    "TournamentEnded(uint256,address,uint256)": TypedContractEvent<
      TournamentEndedEvent.InputTuple,
      TournamentEndedEvent.OutputTuple,
      TournamentEndedEvent.OutputObject
    >;
    TournamentEnded: TypedContractEvent<
      TournamentEndedEvent.InputTuple,
      TournamentEndedEvent.OutputTuple,
      TournamentEndedEvent.OutputObject
    >;

    "TournamentStarted(uint256)": TypedContractEvent<
      TournamentStartedEvent.InputTuple,
      TournamentStartedEvent.OutputTuple,
      TournamentStartedEvent.OutputObject
    >;
    TournamentStarted: TypedContractEvent<
      TournamentStartedEvent.InputTuple,
      TournamentStartedEvent.OutputTuple,
      TournamentStartedEvent.OutputObject
    >;
  };
}
