/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TournamentManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
<<<<<<< HEAD
      | "cancelTournament"
      | "createTournament"
      | "distributePrizes"
      | "isPlayerInTournament"
      | "joinTournament"
      | "owner"
=======
      | "calculatePrizes"
      | "completeTournament"
      | "createTournament"
      | "emergencyWithdraw"
      | "getTournament"
      | "getTournamentPlayers"
      | "getTournamentResults"
      | "hasPlayerJoined"
      | "joinTournament"
      | "owner"
      | "playerJoined"
      | "startTournament"
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
      | "tournamentCount"
      | "tournaments"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PlayerJoined"
<<<<<<< HEAD
      | "TournamentCancelled"
      | "TournamentCreated"
      | "TournamentEnded"
=======
      | "PrizeDistributed"
      | "TournamentCompleted"
      | "TournamentCreated"
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
      | "TournamentStarted"
  ): EventFragment;

  encodeFunctionData(
<<<<<<< HEAD
    functionFragment: "cancelTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTournament",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributePrizes",
    values: [BigNumberish, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPlayerInTournament",
=======
    functionFragment: "calculatePrizes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTournament",
    values: [BigNumberish, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTournament",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTournamentPlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTournamentResults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPlayerJoined",
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
<<<<<<< HEAD
=======
    functionFragment: "playerJoined",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    functionFragment: "tournamentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tournaments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
<<<<<<< HEAD
    functionFragment: "cancelTournament",
=======
    functionFragment: "calculatePrizes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeTournament",
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
<<<<<<< HEAD
    functionFragment: "distributePrizes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPlayerInTournament",
=======
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTournamentPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTournamentResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPlayerJoined",
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "joinTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
<<<<<<< HEAD
=======
    functionFragment: "playerJoined",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    functionFragment: "tournamentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournaments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace PlayerJoinedEvent {
<<<<<<< HEAD
  export type InputTuple = [tournamentId: BigNumberish, player: AddressLike];
  export type OutputTuple = [tournamentId: bigint, player: string];
  export interface OutputObject {
    tournamentId: bigint;
    player: string;
=======
  export type InputTuple = [
    tournamentId: BigNumberish,
    player: AddressLike,
    currentPlayers: BigNumberish,
    maxPlayers: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    player: string,
    currentPlayers: bigint,
    maxPlayers: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    player: string;
    currentPlayers: bigint;
    maxPlayers: bigint;
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

<<<<<<< HEAD
export namespace TournamentCancelledEvent {
  export type InputTuple = [tournamentId: BigNumberish];
  export type OutputTuple = [tournamentId: bigint];
  export interface OutputObject {
    tournamentId: bigint;
=======
export namespace PrizeDistributedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    place: string
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    recipient: string,
    amount: bigint,
    place: string
  ];
  export interface OutputObject {
    tournamentId: bigint;
    recipient: string;
    amount: bigint;
    place: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentCompletedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    firstPlace: AddressLike,
    secondPlace: AddressLike,
    thirdPlace: AddressLike,
    firstPrize: BigNumberish,
    secondPrize: BigNumberish,
    thirdPrize: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    firstPlace: string,
    secondPlace: string,
    thirdPlace: string,
    firstPrize: bigint,
    secondPrize: bigint,
    thirdPrize: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    firstPlace: string;
    secondPlace: string;
    thirdPlace: string;
    firstPrize: bigint;
    secondPrize: bigint;
    thirdPrize: bigint;
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentCreatedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    creator: AddressLike,
<<<<<<< HEAD
    entryFee: BigNumberish,
    size: BigNumberish
=======
    size: BigNumberish,
    entryFee: BigNumberish,
    entryToken: AddressLike
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    creator: string,
<<<<<<< HEAD
    entryFee: bigint,
    size: bigint
=======
    size: bigint,
    entryFee: bigint,
    entryToken: string
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
  ];
  export interface OutputObject {
    tournamentId: bigint;
    creator: string;
<<<<<<< HEAD
    entryFee: bigint;
    size: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentEndedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    winner: AddressLike,
    prizeAmount: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    winner: string,
    prizeAmount: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    winner: string;
    prizeAmount: bigint;
=======
    size: bigint;
    entryFee: bigint;
    entryToken: string;
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentStartedEvent {
  export type InputTuple = [tournamentId: BigNumberish];
  export type OutputTuple = [tournamentId: bigint];
  export interface OutputObject {
    tournamentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TournamentManager extends BaseContract {
  connect(runner?: ContractRunner | null): TournamentManager;
  waitForDeployment(): Promise<this>;

  interface: TournamentManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

<<<<<<< HEAD
  cancelTournament: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTournament: TypedContractMethod<
    [size: BigNumberish, entryFee: BigNumberish, entryToken: AddressLike],
    [bigint],
    "nonpayable"
  >;

  distributePrizes: TypedContractMethod<
=======
  calculatePrizes: TypedContractMethod<
    [tournamentId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        firstPrize: bigint;
        secondPrize: bigint;
        thirdPrize: bigint;
      }
    ],
    "view"
  >;

  completeTournament: TypedContractMethod<
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    [
      tournamentId: BigNumberish,
      firstPlace: AddressLike,
      secondPlace: AddressLike,
      thirdPlace: AddressLike
    ],
    [void],
    "nonpayable"
  >;

<<<<<<< HEAD
  isPlayerInTournament: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
=======
  createTournament: TypedContractMethod<
    [
      size: BigNumberish,
      entryFee: BigNumberish,
      entryToken: AddressLike,
      firstPlacePct: BigNumberish,
      secondPlacePct: BigNumberish,
      thirdPlacePct: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTournament: TypedContractMethod<
    [tournamentId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, string, bigint, bigint] & {
        creator: string;
        createdAt: bigint;
        size: bigint;
        status: bigint;
        entryFee: bigint;
        entryToken: string;
        playerCount: bigint;
        totalPrizePool: bigint;
      }
    ],
    "view"
  >;

  getTournamentPlayers: TypedContractMethod<
    [tournamentId: BigNumberish],
    [string[]],
    "view"
  >;

  getTournamentResults: TypedContractMethod<
    [tournamentId: BigNumberish],
    [
      [string, string, string] & {
        firstPlace: string;
        secondPlace: string;
        thirdPlace: string;
      }
    ],
    "view"
  >;

  hasPlayerJoined: TypedContractMethod<
    [tournamentId: BigNumberish, player: AddressLike],
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    [boolean],
    "view"
  >;

  joinTournament: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

<<<<<<< HEAD
=======
  playerJoined: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  startTournament: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
  tournamentCount: TypedContractMethod<[], [bigint], "view">;

  tournaments: TypedContractMethod<
    [arg0: BigNumberish],
    [
<<<<<<< HEAD
      [string, bigint, string, bigint, bigint, bigint, bigint, string] & {
        creator: string;
        entryFee: bigint;
        entryToken: string;
        size: bigint;
        playerCount: bigint;
        state: bigint;
        totalPrizePool: bigint;
        winner: string;
=======
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        creator: string;
        createdAt: bigint;
        size: bigint;
        status: bigint;
        firstPlacePct: bigint;
        secondPlacePct: bigint;
        thirdPlacePct: bigint;
        entryFee: bigint;
        entryToken: string;
        firstPlaceWinner: string;
        secondPlaceWinner: string;
        thirdPlaceWinner: string;
        totalPrizePool: bigint;
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
<<<<<<< HEAD
    nameOrSignature: "cancelTournament"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTournament"
  ): TypedContractMethod<
    [size: BigNumberish, entryFee: BigNumberish, entryToken: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributePrizes"
=======
    nameOrSignature: "calculatePrizes"
  ): TypedContractMethod<
    [tournamentId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        firstPrize: bigint;
        secondPrize: bigint;
        thirdPrize: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeTournament"
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
  ): TypedContractMethod<
    [
      tournamentId: BigNumberish,
      firstPlace: AddressLike,
      secondPlace: AddressLike,
      thirdPlace: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
<<<<<<< HEAD
    nameOrSignature: "isPlayerInTournament"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
=======
    nameOrSignature: "createTournament"
  ): TypedContractMethod<
    [
      size: BigNumberish,
      entryFee: BigNumberish,
      entryToken: AddressLike,
      firstPlacePct: BigNumberish,
      secondPlacePct: BigNumberish,
      thirdPlacePct: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTournament"
  ): TypedContractMethod<
    [tournamentId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, string, bigint, bigint] & {
        creator: string;
        createdAt: bigint;
        size: bigint;
        status: bigint;
        entryFee: bigint;
        entryToken: string;
        playerCount: bigint;
        totalPrizePool: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTournamentPlayers"
  ): TypedContractMethod<[tournamentId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTournamentResults"
  ): TypedContractMethod<
    [tournamentId: BigNumberish],
    [
      [string, string, string] & {
        firstPlace: string;
        secondPlace: string;
        thirdPlace: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPlayerJoined"
  ): TypedContractMethod<
    [tournamentId: BigNumberish, player: AddressLike],
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinTournament"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
<<<<<<< HEAD
=======
    nameOrSignature: "playerJoined"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "startTournament"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    nameOrSignature: "tournamentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tournaments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
<<<<<<< HEAD
      [string, bigint, string, bigint, bigint, bigint, bigint, string] & {
        creator: string;
        entryFee: bigint;
        entryToken: string;
        size: bigint;
        playerCount: bigint;
        state: bigint;
        totalPrizePool: bigint;
        winner: string;
=======
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        creator: string;
        createdAt: bigint;
        size: bigint;
        status: bigint;
        firstPlacePct: bigint;
        secondPlacePct: bigint;
        thirdPlacePct: bigint;
        entryFee: bigint;
        entryToken: string;
        firstPlaceWinner: string;
        secondPlaceWinner: string;
        thirdPlaceWinner: string;
        totalPrizePool: bigint;
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;
  getEvent(
<<<<<<< HEAD
    key: "TournamentCancelled"
  ): TypedContractEvent<
    TournamentCancelledEvent.InputTuple,
    TournamentCancelledEvent.OutputTuple,
    TournamentCancelledEvent.OutputObject
=======
    key: "PrizeDistributed"
  ): TypedContractEvent<
    PrizeDistributedEvent.InputTuple,
    PrizeDistributedEvent.OutputTuple,
    PrizeDistributedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentCompleted"
  ): TypedContractEvent<
    TournamentCompletedEvent.InputTuple,
    TournamentCompletedEvent.OutputTuple,
    TournamentCompletedEvent.OutputObject
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
  >;
  getEvent(
    key: "TournamentCreated"
  ): TypedContractEvent<
    TournamentCreatedEvent.InputTuple,
    TournamentCreatedEvent.OutputTuple,
    TournamentCreatedEvent.OutputObject
  >;
  getEvent(
<<<<<<< HEAD
    key: "TournamentEnded"
  ): TypedContractEvent<
    TournamentEndedEvent.InputTuple,
    TournamentEndedEvent.OutputTuple,
    TournamentEndedEvent.OutputObject
  >;
  getEvent(
=======
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    key: "TournamentStarted"
  ): TypedContractEvent<
    TournamentStartedEvent.InputTuple,
    TournamentStartedEvent.OutputTuple,
    TournamentStartedEvent.OutputObject
  >;

  filters: {
<<<<<<< HEAD
    "PlayerJoined(uint256,address)": TypedContractEvent<
=======
    "PlayerJoined(uint256,address,uint256,uint256)": TypedContractEvent<
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;

<<<<<<< HEAD
    "TournamentCancelled(uint256)": TypedContractEvent<
      TournamentCancelledEvent.InputTuple,
      TournamentCancelledEvent.OutputTuple,
      TournamentCancelledEvent.OutputObject
    >;
    TournamentCancelled: TypedContractEvent<
      TournamentCancelledEvent.InputTuple,
      TournamentCancelledEvent.OutputTuple,
      TournamentCancelledEvent.OutputObject
    >;

    "TournamentCreated(uint256,address,uint256,uint8)": TypedContractEvent<
=======
    "PrizeDistributed(uint256,address,uint256,string)": TypedContractEvent<
      PrizeDistributedEvent.InputTuple,
      PrizeDistributedEvent.OutputTuple,
      PrizeDistributedEvent.OutputObject
    >;
    PrizeDistributed: TypedContractEvent<
      PrizeDistributedEvent.InputTuple,
      PrizeDistributedEvent.OutputTuple,
      PrizeDistributedEvent.OutputObject
    >;

    "TournamentCompleted(uint256,address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      TournamentCompletedEvent.InputTuple,
      TournamentCompletedEvent.OutputTuple,
      TournamentCompletedEvent.OutputObject
    >;
    TournamentCompleted: TypedContractEvent<
      TournamentCompletedEvent.InputTuple,
      TournamentCompletedEvent.OutputTuple,
      TournamentCompletedEvent.OutputObject
    >;

    "TournamentCreated(uint256,address,uint8,uint256,address)": TypedContractEvent<
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;
    TournamentCreated: TypedContractEvent<
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;

<<<<<<< HEAD
    "TournamentEnded(uint256,address,uint256)": TypedContractEvent<
      TournamentEndedEvent.InputTuple,
      TournamentEndedEvent.OutputTuple,
      TournamentEndedEvent.OutputObject
    >;
    TournamentEnded: TypedContractEvent<
      TournamentEndedEvent.InputTuple,
      TournamentEndedEvent.OutputTuple,
      TournamentEndedEvent.OutputObject
    >;

=======
>>>>>>> 1c074842c42dc46c79660c9f01bf39b779cc4e4c
    "TournamentStarted(uint256)": TypedContractEvent<
      TournamentStartedEvent.InputTuple,
      TournamentStartedEvent.OutputTuple,
      TournamentStartedEvent.OutputObject
    >;
    TournamentStarted: TypedContractEvent<
      TournamentStartedEvent.InputTuple,
      TournamentStartedEvent.OutputTuple,
      TournamentStartedEvent.OutputObject
    >;
  };
}
